name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: "20"
  APP_NAME: cron-ticker

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BUILD_DIR: dist

    steps:
      - uses: actions/checkout@v4

      - name: Show Variables
        run: |
          echo "App: ${{ env.APP_NAME }}, Node: ${{ env.NODE_VERSION }}"
          echo "Build Directory: ${{ env.BUILD_DIR }}"

      - name: Show Github Variables
        run: |
          echo "App version: ${{ vars.APP_VERSION }}"

      - name: Show Node Version
        run: |
          echo "Node version: ${{ vars.APP_NODE_VERSION }}"

      - name: Build
        run: npm run build
        env:
          APP_VERSION: '2.0.0'