name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: "20"
  APP_NAME: cron-ticker

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BUILD_DIR: dist

    steps:
      - uses: actions/checkout@v4

      - name: Mostrar Variables
        run: |
          echo "App: ${APP_NAME}, Node: ${NODE_VERSION}"

      
      - name: Construir
        run: npm run build
        env:
          APP_VERSION: '2.0.0'
        